In [9]:
import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split

In [6]:
csv_df = pd.read_csv('samsung.csv')
csv_df

,Unnamed: 0,ROE,영업이익률,부채비율,EPS,순이익률,BPS,종가,PER,PBR,PER.1,PBR.1,PER.2,PBR.2
0,20221231,16.42,14.35,26.41,8057.0,18.41,51356.84,55300.0,6.86,1.08,6.86,1.08,6.86,1.08
1,20211231,13.58,18.47,39.92,5777.0,14.27,44137.30,78300.0,13.55,1.77,13.55,1.77,13.55,1.77
2,20201231,9.71,15.20,37.07,3841.0,11.15,40136.44,81000.0,21.09,2.02,21.09,2.02,21.09,2.02
3,20191231,8.51,12.05,34.12,3166.0,9.44,38285.32,55800.0,17.62,1.46,17.62,1.46,17.62,1.46
4,20181231,18.20,24.16,36.97,6461.0,18.19,36097.38,38700.0,5.99,1.07,5.99,1.07,5.99,1.07
5,20171231,19.47,22.39,40.68,5997.0,17.61,30490.74,50960.0,8.50,1.67,8.50,1.67,8.50,1.67
6,20161231,11.72,14.49,35.87,3159.0,11.26,26822.48,36040.0,11.41,1.34,11.41,1.34,11.41,1.34
7,20151231,10.25,13.16,35.25,126305.0,9.50,1186567.57,25200.0,0.20,0.02,0.20,0.02,0.20,0.02
8,20141231,13.73,12.14,37.08,153105.0,11.35,1100057.63,26540.0,0.17,0.02,0.17,0.02,0.17,0.02
9,20131231,20.38,16.08,42.70,197841.0,13.33,973898.19,27440.0,0.14,0.03,0.14,0.03,0.14,0.03

In [8]:
# 날짜 인덱스가 없음 일단 임시로
csv_df = csv_df.rename(columns={'Unnamed: 0':"날짜"})
csv_df

,날짜,ROE,영업이익률,부채비율,EPS,순이익률,BPS,종가,PER,PBR,PER.1,PBR.1,PER.2,PBR.2
0,20221231,16.42,14.35,26.41,8057.0,18.41,51356.84,55300.0,6.86,1.08,6.86,1.08,6.86,1.08
1,20211231,13.58,18.47,39.92,5777.0,14.27,44137.30,78300.0,13.55,1.77,13.55,1.77,13.55,1.77
2,20201231,9.71,15.20,37.07,3841.0,11.15,40136.44,81000.0,21.09,2.02,21.09,2.02,21.09,2.02
3,20191231,8.51,12.05,34.12,3166.0,9.44,38285.32,55800.0,17.62,1.46,17.62,1.46,17.62,1.46
4,20181231,18.20,24.16,36.97,6461.0,18.19,36097.38,38700.0,5.99,1.07,5.99,1.07,5.99,1.07
5,20171231,19.47,22.39,40.68,5997.0,17.61,30490.74,50960.0,8.50,1.67,8.50,1.67,8.50,1.67
6,20161231,11.72,14.49,35.87,3159.0,11.26,26822.48,36040.0,11.41,1.34,11.41,1.34,11.41,1.34
7,20151231,10.25,13.16,35.25,126305.0,9.50,1186567.57,25200.0,0.20,0.02,0.20,0.02,0.20,0.02
8,20141231,13.73,12.14,37.08,153105.0,11.35,1100057.63,26540.0,0.17,0.02,0.17,0.02,0.17,0.02
9,20131231,20.38,16.08,42.70,197841.0,13.33,973898.19,27440.0,0.14,0.03,0.14,0.03,0.14,0.03

In [13]:
# 학습과 테스트 데이터 세트를 분리해 학습과 예측 수행
y = csv_df['종가']

X = csv_df.drop(['PER.1','PBR.1','PER.2','PBR.2','종가'],axis=1,inplace = False)

# train set 7  대 test set 3, random_state : 호출할 때마다 동일한 학습/테스트용 데이터 세트를 생성하기 위한 난수 값
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=156)

In [14]:
# sklearn 사용하여 선형 회귀 모델 구하기
lr = LinearRegression()
ridge = Ridge(alpha=10)
lasso = Lasso(alpha=0.01)

lr.fit(X_train, y_train)
ridge.fit(X_train, y_train)
lasso.fit(X_train, y_train)

# 테스트셋의 날짜도 랜덤으로 뽑아서 시각화하기 위해 날짜로 미리 정렬했는데 문제가 있을까? 일단 없는 것 같음
X_test = X_test.sort_index()

In [15]:
# 예측 수행
y_pred = lr.predict(X_test)
y_pred_ridge = ridge.predict(X_test)
y_pred_lasso = lasso.predict(X_test)

# 평가 지표
# MSE실제 값과 예측 : 값의 차이를 제곱해서 평균
# RMSE : MSE에 루트를 씌운 것 
# r2 : 분산 기반으로 예측 성능 평가. 1에 가까울수록 예측 정확도 높음
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2= r2_score(y_test,y_pred)
print("---------------------------")
print("선형 회귀")
print('MSE', mse)
print('RMSE:', rmse)
print('Variance score(r2):', r2)
print("---------------------------")

mse_ridge = mean_squared_error(y_test, y_pred_ridge)
rmse_ridge = np.sqrt(mse_ridge)
r2_ridge= r2_score(y_test,y_pred_ridge)
print("Ridge")
print('MSE', mse_ridge)
print('RMSE:', rmse_ridge)
print('Variance score(r2):', r2_ridge)
print("---------------------------")

mse_lasso = mean_squared_error(y_test, y_pred_lasso)
rmse_lasso = np.sqrt(mse_lasso)
r2_lasso= r2_score(y_test,y_pred_lasso)
print("Lasso")
print('MSE', mse_lasso)
print('RMSE:', rmse_lasso)
print('Variance score(r2):', r2_lasso)
print("---------------------------")

# 값 봐라... 이게 음수가 나올 수 있는 건가? 쨌던 회귀는 쓸만한 모델이 아니다!!

---------------------------
선형 회귀
MSE 61274964.53494786
RMSE: 7827.832684399166
Variance score(r2): -33.64015180900439
---------------------------
Ridge
MSE 90725668.53279978
RMSE: 9525.002285186067
Variance score(r2): -50.28931456430538
---------------------------
Lasso
MSE 62762744.32901686
RMSE: 7922.294132952706
Variance score(r2): -34.48122806773524
---------------------------